# Site settings
title: Easy Life
email: l02n20l@qq.com
description: "This is All About Jimmy Lee"
baseurl: ""
url: "http://www.handos.info"
twitter_username: l02n20l
github_username:  jimmyleeking

# Build settings
markdown: kramdown
permalink: pretty
