# Site settings
title: HandOS
email: l02n20l@qq.com
description: "技术，思想，追求。"
baseurl: ""
url: "http://www.handos.info"
twitter_username: l02n20l
github_username:  jimmyleeking

# Build settings
markdown: kramdown
permalink: pretty
